
//Error Contants
export const GET_ERRORS = "GET_ERRORS" 
export const CLEAR_ERRORS = "CLEAR_ERRORS"

// Auth Constants

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const DELETE_USER="DELETE_USER"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"
export const UPDATE_USER="UPDATE_USER"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"

export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS"

// doctor constants
export const GET_DOCTORS="GET_DOCTORS"
export const GET_DOCTORS_SUCCESS="GET_DOCTORS_SUCCESS"
export const GET_DOCTORS_FAIL="GET_DOCTORS_FAIL"

// appointments constants
export const GET_APPOINTMENT = "GET_APPOINTMENT"
export const GET_APPOINTMENT_SUCCESS="GET_APPOINTMENT_SUCCESS"
export const DELETE_APPOINTMENT="DELETE_APPOINTMENT"
export const DELETE_APPOINTMENT_SUCCESS="DELETE_APPOINTMENT_SUCCESS"
export const DELETE_APPOINTMENT_FAIL="DELETE_APPOINTMENT_FAIL"
export const CONFIRM_APPOINTMENT="CONFIRM_APPOINTMENT"
export const CONFIRM_APPOINTMENT_SUCCESS="CONFIRM_APPOINTMENT_SUCCESS"
export const CONFIRM_APPOINTMENT_FAIL="CONFIRM_APPOINTMENT_FAIL"